---
extends:
  - stylelint-config-recommended
  - stylelint-config-standard
  - stylelint-config-styled-components
plugins:
  - stylelint-config-rational-order/plugin
  - stylelint-no-unsupported-browser-features
  - stylelint-order
ignoreFiles:
  - node_modules/**/*
  - dist/**/*
  - "**/*.d.ts"
rules:
  order/properties-order:
    - []
    - unspecified: bottom
      emptyLineMinimumPropertyThreshold: 4
  plugin/no-unsupported-browser-features:
    - true
    - browsers:
        - last 2 major versions and >5% in US and not dead and not IE > 0
  plugin/rational-order:
    - true
    - empty-line-between-groups: threshold
      empty-line-property-threshold: 3
      empty-lines-within-groups: false
      empty-line-before-unspecified: always
      property-order: flexible
      unspecified: bottomAlphabetical
  block-no-empty: null
  color-hex-case: upper
  declaration-colon-newline-after: null
  declaration-empty-line-before: null
  font-family-no-missing-generic-family-keyword: null
  function-name-case: null
  indentation: 2
  no-eol-whitespace: null
  no-extra-semicolons: null
  no-missing-end-of-source-newline: null
  selector-max-empty-lines: 2
  value-keyword-case: null
  value-list-comma-newline-after: null
